### PR TITLE
set mate menu design of top panel

### PR DESCRIPTION
**Pull request by luigifab**
I will search later for the space between sensors and system monitor.

gtk2

gtk3

### CODE REVIEW

**Comment by mk-fg** [comment]
Thanks!

Do you debug Mate bar via passing GTK_DEBUG=interactive in its environment too?
Just curious as suspect it might be started from somewhere deeper within DE than most usual apps.

**Comment by luigifab** [comment]
Yes, I added it in _/etc/environment_.

**Comment by mk-fg** [comment]
Ah, gotcha, makes sense.

**Comment by mk-fg** [comment]
Getting to compare ubuntu-mate 16.04 vs 19.10 looks with the theme just now, found this guide on how to maybe make such debugging a bit easier:
https://ubuntu-mate.community/t/mate-18-04-indicator-applet-complete-1-20-0-icons-resize-issue/16807/10

Did test it on 19.10 - works well, and very convenient to use with the hotkey, which seem to work well even in various menus.

**Comment by mk-fg** [comment]
Added link and gist of that to README as well, to avoid needing to google this later:
https://github.com/mk-fg/clearlooks-phenix-humanity/#user-content-gtk-inspector-on-ubuntu-mate

**Pull request merged**
