### PR TITLE
create and use svg for radio and checkbox

### PR DESCRIPTION
**Pull request by luigifab**
gtk2-3

### CODE REVIEW

**Comment by mk-fg** [comment]
Thanks, those look great.
There are source svg's for those pngs in _src/ dir, which guess I'll cleanup as well.

Do you know why original theme used .png files rendered for different resolutions and not .svg ones directly?

Two reasons I can think of off the top of my head are:

- SVG was not directly (or well-) supported in some old-ish GTK3 version when theme was originally implemented.

- `inkscape --export-png` might produce better versions (e.g. sharper or something) of these SVG files than GTK3 cairo renderer would (or at least it used to in older GTK3 versions).

Suspect that jpfleury/clearlooks-phenix repo history and old Issues/PRs there might give a clue, but didn't look into it. Mostly just curious.

**Comment by mk-fg** [comment]
GTK2 version also seem to have slight :hover highlight on the whole checkbutton/radiobutton thing and light-shadow behind :disabled icons, similar to text, which should probably be easy to add.
Will try to do when I'll get to it after other more broken stuff, and unless you beat me to it, I guess :)

shot-2020-02-23_22-58-56

**Comment by luigifab** [comment]
I see in GTK documentation that [SVG support is optional](https://developer.gnome.org/icon-theme-spec/), and in another page, [loading png is faster than loading svg](https://developer.gnome.org/gtk3/stable/gtk-encode-symbolic-svg.html). I also think that png export can make better version.

For the hover effect (and the focus border), I will try later :)

**Comment by mk-fg** [comment]
> I see in GTK documentation that SVG support is optional
> (link used there: https://developer.gnome.org/icon-theme-spec/ )

Don't think that's related to GTK - it's an Icon Theme Specification, and these are entirely separate things from GTK2/GTK3 themes, so stuff there should not apply here.

**Comment by mk-fg** [comment]
> Icon Theme Specification

To clarify - these live in $HOME/.icons and I think supposed to apply to all DEs and toolkits, as it's a freedesktop specification (canonical URL - https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html ), not just to GNOME or anything GTK-based.

**Comment by mk-fg** [comment]
> and light-shadow behind :disabled icons

This one is actually what murrine does when drawing pretty much every border with reliefstyle=2 (in gtk-2.0/gtkrc here, via murrine_draw_inset), and I think maybe too minor a detail to add SVG or PNG borders everywhere over (instead of just using css "border" + "border-radius").

**Comment by mk-fg** [comment]
:disabled text shadows (or highlights rather) were also broken in image above (and everywhere, not just for these switch-thingies), should be fixed by fb252f2

**Comment by mk-fg** [comment]
> loading png is faster than loading svg. I also think that png export can make better version.

Didn't consider performance, but I think that might be a good reason to use png indeed, all other things being equal of course - i.e. at least for pixel-precise elements, which won't be stretched.

**Comment by mk-fg** [comment]
> > and light-shadow behind :disabled icons
> 
> This one is actually what murrine does when drawing pretty much every border with reliefstyle=2 (in gtk-2.0/gtkrc here, via murrine_draw_inset), and I think maybe too minor a detail to add SVG or PNG borders everywhere over (instead of just using css "border" + "border-radius").

Correction: I think box-shadow will work for most of these cases just fine, will look into adding these later.

**Pull request merged**
